Using TensorFlow backend.
8 cores
Building a vocabulary...
Vocabulary built for the first time in 8297.11001753807
Doc2Vec(dm/c,d100,n5,w5,mc2,s0.001,t8)
Doc2Vec(dm/c,d100,n5,w5,mc2,s0.001,t8)
Doc2Vec(dbow,d100,n5,mc2,s0.001,t8)
Doc2Vec(dm/m,d100,n5,w10,mc2,s0.001,t8)
dbow+dmm
dbow+dmc
START 2017-08-12 19:56:21.858528
Traceback (most recent call last):
  File "doc2vec.py", line 164, in <module>
    err, err_count, test_count, predictor = error_rate_for_model(train_model, train_docs, test_docs)
  File "doc2vec.py", line 133, in error_rate_for_model
    corrects = sum(np.rint(test_predictions) == [doc.sentiment for doc in test_data])
NameError: name 'test_data' is not defined
Using TensorFlow backend.
8 cores
Building a vocabulary...
Vocabulary built for the first time in 8669.299710512161
Doc2Vec(dm/c,d100,n5,w5,mc2,s0.001,t8)
Doc2Vec(dm/c,d100,n5,w5,mc2,s0.001,t8)
Doc2Vec(dbow,d100,n5,mc2,s0.001,t8)
Doc2Vec(dm/m,d100,n5,w10,mc2,s0.001,t8)
dbow+dmm
dbow+dmc
START 2017-08-13 03:50:16.345374
Traceback (most recent call last):
  File "doc2vec.py", line 164, in <module>
    err, err_count, test_count, predictor = error_rate_for_model(train_model, train_docs, test_docs)
  File "doc2vec.py", line 133, in error_rate_for_model
    corrects = sum(np.rint(test_predictions) == [doc.sentiment for doc in test_set])
TypeError: 'bool' object is not iterable
Using TensorFlow backend.
8 cores
Building a vocabulary...
Vocabulary built for the first time in 8755.221606731415
Doc2Vec(dm/c,d100,n5,w5,mc2,s0.001,t8)
Doc2Vec(dm/c,d100,n5,w5,mc2,s0.001,t8)
Doc2Vec(dbow,d100,n5,mc2,s0.001,t8)
Doc2Vec(dm/m,d100,n5,w10,mc2,s0.001,t8)
dbow+dmm
dbow+dmc
START 2017-08-13 05:13:03.222483
Traceback (most recent call last):
  File "doc2vec.py", line 164, in <module>
    err, err_count, test_count, predictor = error_rate_for_model(train_model, train_docs, test_docs)
  File "doc2vec.py", line 133, in error_rate_for_model
    corrects = sum(np.rint(test_predictions) == [doc.sentiment for doc in test_set])
TypeError: 'bool' object is not iterable
